package com.zhangke.fread.localization

val localizedString = Res.string

/**
 * generated by LLM
 */
object LocalizedString {

    val skip = localizedString.skip
    val alert = localizedString.alert
    val durationMinute = localizedString.duration_minute
    val durationHour = localizedString.duration_hour
    val durationDay = localizedString.duration_day
    val durationWeek = localizedString.duration_week
    val cancel = localizedString.cancel
    val ok = localizedString.ok
    val empty = localizedString.empty
    val durationSelectorTitle = localizedString.duration_selector_title
    val retry = localizedString.retry
    val loadMoreError = localizedString.load_more_error
    val unknownError = localizedString.unknown_error
    val networkError = localizedString.network_error
    val resourceNotFound = localizedString.resource_not_found
    val imageSaving = localizedString.image_saving
    val imageSaveSuccess = localizedString.image_save_success
    val imageSaveFailed = localizedString.image_save_failed
    val permissionWriteExternalPermissionDenied =
        localizedString.permission_write_external_permission_denied
    val feedsLoadPreviousPageLabel = localizedString.feeds_load_previous_page_label
    val feedsLoadPreviousPageFailedLabel = localizedString.feeds_load_previous_page_failed_label
    val image = localizedString.image
    val video = localizedString.video
    val login = localizedString.login
    val add = localizedString.add
    val search = localizedString.search
    val authSuccess = localizedString.auth_success
    val authFailed = localizedString.auth_failed
    val select = localizedString.select
    val logout = localizedString.logout
    val settings = localizedString.settings
    val donate = localizedString.donate
    val feeds = localizedString.feeds
    val save = localizedString.save
    val done = localizedString.done
    val blueskyName = localizedString.bluesky_name
    val blueskyDescription = localizedString.bluesky_description
    val mastodonName = localizedString.mastodon_name
    val mastodonDescription = localizedString.mastodon_description
    val mixedContentName = localizedString.mixed_content_name
    val mixedContentDescription = localizedString.mixed_content_description
    val statusProviderTypeActivityPub = localizedString.status_provider_type_activity_pub
    val addContentTitle = localizedString.add_content_title
    val addContentSuccessWithAccount = localizedString.add_content_success_with_account
    val addContentSuccessWithLoginReminder = localizedString.add_content_success_with_login_reminder
    val contentExistTips = localizedString.content_exist_tips
    val contentAddSuccess = localizedString.content_add_success
    val addFeedsPageEmptyNameExist = localizedString.add_feeds_page_empty_name_exist
    val editProfileNameEmpty = localizedString.edit_profile_name_empty
    val editProfileLabelName = localizedString.edit_profile_label_name
    val editProfileLabelNote = localizedString.edit_profile_label_note
    val editProfileInputNameHint = localizedString.edit_profile_input_name_hint
    val editProfileInputNoteHint = localizedString.edit_profile_input_note_hint
    val editProfileEditConfirmMessage = localizedString.edit_profile_edit_confirm_message
    val addContentSuccessSnackbar = localizedString.add_content_success_snackbar
    val sharedSelectLanguageTitle = localizedString.shared_select_language_title
    val sharedStatusContextScreenTitle = localizedString.shared_status_context_screen_title
    val sharedAltLabel = localizedString.shared_alt_label
    val loginDialogInputHint = localizedString.login_dialog_input_hint
    val loginDialogTitle = localizedString.login_dialog_title
    val loginDialogInputTip = localizedString.login_dialog_input_tip
    val loginDialogInputTitle = localizedString.login_dialog_input_title
    val loginDialogInputLabel = localizedString.login_dialog_input_label
    val loginDialogTargetTitle = localizedString.login_dialog_target_title
    val profileDescription = localizedString.profile_description
    val listContentEmptyPlaceholder = localizedString.list_content_empty_placeholder
    val sharedNotificationUnknownDesc = localizedString.shared_notification_unknown_desc
    val sharedNotificationFavouritedDesc = localizedString.shared_notification_favourited_desc
    val sharedNotificationReblogDesc = localizedString.shared_notification_reblog_desc
    val sharedNotificationPollDesc = localizedString.shared_notification_poll_desc
    val sharedNotificationPollCount = localizedString.shared_notification_poll_count
    val sharedNotificationFollowDesc = localizedString.shared_notification_follow_desc
    val sharedNotificationUpdateDesc = localizedString.shared_notification_update_desc
    val sharedNotificationFollowRequest = localizedString.shared_notification_follow_request
    val sharedNotificationNewStatusDesc = localizedString.shared_notification_new_status_desc
    val sharedNotificationSeveredDesc = localizedString.shared_notification_severed_desc
    val sharedNotificationQuoteDesc = localizedString.shared_notification_quote_desc
    val sharedNotificationReplyDesc = localizedString.shared_notification_reply_desc
    val sharedUserListTitleFollowing = localizedString.shared_user_list_title_following
    val sharedUserListTitleFollowers = localizedString.shared_user_list_title_followers
    val sharedUserListTitleMutes = localizedString.shared_user_list_title_mutes
    val sharedUserListTitleBlocks = localizedString.shared_user_list_title_blocks
    val sharedUserListTitleLikes = localizedString.shared_user_list_title_likes
    val sharedUserListTitleReblog = localizedString.shared_user_list_title_reblog
    val sharedUserListActionMute = localizedString.shared_user_list_action_mute
    val sharedUserListActionBlock = localizedString.shared_user_list_action_block
    val sharedUserListActionMuted = localizedString.shared_user_list_action_muted
    val sharedUserListActionBlocked = localizedString.shared_user_list_action_blocked
    val sharedUserListActionMuteDialogMessage =
        localizedString.shared_user_list_action_mute_dialog_message
    val sharedUserListActionBlockDialogMessage =
        localizedString.shared_user_list_action_block_dialog_message
    val sharedPublishBlogTitle = localizedString.shared_publish_blog_title
    val sharedPublishBlogTextHint = localizedString.shared_publish_blog_text_hint
    val sharedPublishReplyInputHint = localizedString.shared_publish_reply_input_hint
    val sharedPublishInteractionNoLimit = localizedString.shared_publish_interaction_no_limit
    val sharedPublishInteractionLimited = localizedString.shared_publish_interaction_limited
    val sharedPublishInteractionDialogTitle =
        localizedString.shared_publish_interaction_dialog_title
    val sharedPublishInteractionDialogSubtitle =
        localizedString.shared_publish_interaction_dialog_subtitle
    val sharedPublishInteractionDialogQuoteTitle =
        localizedString.shared_publish_interaction_dialog_quote_title
    val sharedPublishInteractionDialogQuoteAllow =
        localizedString.shared_publish_interaction_dialog_quote_allow
    val sharedPublishInteractionDialogReplyTitle =
        localizedString.shared_publish_interaction_dialog_reply_title
    val sharedPublishInteractionDialogReplySubtitle =
        localizedString.shared_publish_interaction_dialog_reply_subtitle
    val sharedPublishInteractionDialogReplyAll =
        localizedString.shared_publish_interaction_dialog_reply_all
    val sharedPublishInteractionDialogReplyNobody =
        localizedString.shared_publish_interaction_dialog_reply_nobody
    val sharedPublishInteractionDialogReplyCombineTitle =
        localizedString.shared_publish_interaction_dialog_reply_combine_title
    val sharedPublishInteractionDialogMentioned =
        localizedString.shared_publish_interaction_dialog_mentioned
    val sharedPublishInteractionDialogFollowing =
        localizedString.shared_publish_interaction_dialog_following
    val sharedPublishInteractionDialogFollower =
        localizedString.shared_publish_interaction_dialog_follower
    val sharedPublishInteractionDialogInList =
        localizedString.shared_publish_interaction_dialog_in_list
    val sharedPublishMediaAltDialogTitle = localizedString.shared_publish_media_alt_dialog_title
    val sharedPublishMediaAltDialogInputTip =
        localizedString.shared_publish_media_alt_dialog_input_tip
    val sharedPublishMediaAltDialogInputHint =
        localizedString.shared_publish_media_alt_dialog_input_hint
    val sharedFeedsNotLoginTitle = localizedString.shared_feeds_not_login_title
    val sharedFeedsGoToLogin = localizedString.shared_feeds_go_to_login
    val sharedPublishSelectAccountTitle = localizedString.shared_publish_select_account_title
    val postStatusScopePublic = localizedString.post_status_scope_public
    val postStatusScopeUnlisted = localizedString.post_status_scope_unlisted
    val postStatusScopeFollowerOnly = localizedString.post_status_scope_follower_only
    val postStatusScopeMentionedOnly = localizedString.post_status_scope_mentioned_only
    val postStatusContentWarning = localizedString.post_status_content_warning
    val postStatusSuccess = localizedString.post_status_success
    val postStatusFailed = localizedString.post_status_failed
    val postStatusExitDialogContent = localizedString.post_status_exit_dialog_content
    val postStatusContentIsEmpty = localizedString.post_status_content_is_empty
    val postStatusPartFailed = localizedString.post_status_part_failed
    val selectAccountOpenStatusTitle = localizedString.select_account_open_status_title
    val selectAccountOpenStatusEmpty = localizedString.select_account_open_status_empty
    val selectAccountOpenStatusSearchIn = localizedString.select_account_open_status_search_in
    val selectAccountOpenStatusSearchFailed =
        localizedString.select_account_open_status_search_failed
    val status_ui_repost = localizedString.status_ui_repost
    val status_ui_reposted = localizedString.status_ui_reposted
    val statusUiQuote = localizedString.status_ui_quote
    val statusUiLike = localizedString.status_ui_like
    val statusUiComment = localizedString.status_ui_comment
    val statusUiDelete = localizedString.status_ui_delete
    val statusUiShare = localizedString.status_ui_share
    val statusUiBookmark = localizedString.status_ui_bookmark
    val statusUiUnbookmark = localizedString.status_ui_unbookmark
    val statusUiReply = localizedString.status_ui_reply
    val statusUiFollow = localizedString.status_ui_follow
    val statusUiUnfollow = localizedString.status_ui_unfollow
    val statusUiPin = localizedString.status_ui_pin
    val statusUiUnpin = localizedString.status_ui_unpin
    val statusUiEdit = localizedString.status_ui_edit
    val statusUiSensitiveByFilter = localizedString.status_ui_sensitive_by_filter
    val statusUiNewStatus = localizedString.status_ui_new_status
    val statusUiDeleteStatusConfirm = localizedString.status_ui_delete_status_confirm
    val statusUiImageSensitiveLabel = localizedString.status_ui_image_sensitive_label
    val statusUiImageContentShowHiddenLabel =
        localizedString.status_ui_image_content_show_hidden_label
    val statusUiImageContentHideHiddenLabel =
        localizedString.status_ui_image_content_hide_hidden_label
    val statusUiPollVote = localizedString.status_ui_poll_vote
    val statusUiPollVoteFinishedTip = localizedString.status_ui_poll_vote_finished_tip
    val statusUiPollVotesFinishedTip = localizedString.status_ui_poll_votes_finished_tip
    val statusUiInteractionOpenInBrowser = localizedString.status_ui_interaction_open_in_browser
    val statusUiInteractionOpenOriginalInstance =
        localizedString.status_ui_interaction_open_original_instance
    val statusUiInteractionCopyUrl = localizedString.status_ui_interaction_copy_url
    val statusUiInteractionTranslate = localizedString.status_ui_interaction_translate
    val statusUiInteractionOpenBlogByOtherAccount =
        localizedString.status_ui_interaction_open_blog_by_other_account
    val statusUiVisibilityMentionedOnly = localizedString.status_ui_visibility_mentioned_only
    val statusUiLabelPinned = localizedString.status_ui_label_pinned
    val statusUiInfoLabelEdited = localizedString.status_ui_info_label_edited
    val statusUiInteractionLabelFavouritedCount =
        localizedString.status_ui_interaction_label_favourited_count
    val statusUiInteractionLabelBoostedCount =
        localizedString.status_ui_interaction_label_boosted_count
    val statusUiBottomLabelEditedAt = localizedString.status_ui_bottom_label_edited_at
    val statusUiTranslating = localizedString.status_ui_translating
    val statusUiTranslateShowOriginal = localizedString.status_ui_translate_show_original
    val statusUiEditContentDeleteDialogContent =
        localizedString.status_ui_edit_content_delete_dialog_content
    val statusUiEditContentNameTitle = localizedString.status_ui_edit_content_name_title
    val statusUiEditContentNameLabel = localizedString.status_ui_edit_content_name_label
    val statusUiEditContentNameHint = localizedString.status_ui_edit_content_name_hint
    val statusUiEditContentConfigShowingListTitle =
        localizedString.status_ui_edit_content_config_showing_list_title
    val statusUiEditContentConfigShowingListDescription =
        localizedString.status_ui_edit_content_config_showing_list_description
    val statusUiEditContentConfigHiddenListTitle =
        localizedString.status_ui_edit_content_config_hidden_list_title
    val statusUiUserDetailRelationshipMutuals =
        localizedString.status_ui_user_detail_relationship_mutuals
    val statusUiUserDetailRelationshipBlocking =
        localizedString.status_ui_user_detail_relationship_blocking
    val statusUiUserDetailRelationshipFollowing =
        localizedString.status_ui_user_detail_relationship_following
    val statusUiUserDetailRelationshipNotFollow =
        localizedString.status_ui_user_detail_relationship_not_follow
    val statusUiUserDetailRelationshipRequested =
        localizedString.status_ui_user_detail_relationship_requested
    val statusUiUserDetailRelationshipFollowBack =
        localizedString.status_ui_user_detail_relationship_follow_back
    val statusUiUserDetailRequestByTip = localizedString.status_ui_user_detail_request_by_tip
    val statusUiRelationshipBtnDialogContentCancelFollow =
        localizedString.status_ui_relationship_btn_dialog_content_cancel_follow
    val statusUiRelationshipBtnDialogContentCancelFollowRequest =
        localizedString.status_ui_relationship_btn_dialog_content_cancel_follow_request
    val statusUiRelationshipBtnDialogContentCancelBlocking =
        localizedString.status_ui_relationship_btn_dialog_content_cancel_blocking
    val statusUiUserDetailFollowsYou = localizedString.status_ui_user_detail_follows_you
    val statusUiUserDetailPosts = localizedString.status_ui_user_detail_posts
    val statusUiUserDetailFollowerInfo = localizedString.status_ui_user_detail_follower_info
    val statusUiUserDetailFollowingInfo = localizedString.status_ui_user_detail_following_info
    val statusUiTopLabelContinuedThread = localizedString.status_ui_top_label_continued_thread
    val statusUiUpdateDialogTitle = localizedString.status_ui_update_dialog_title
    val statusUiUpdateDialogReleaseNote = localizedString.status_ui_update_dialog_release_note
    val statusUiSwitchAccountDialogTitle = localizedString.status_ui_switch_account_dialog_title
    val statusUiLikes = localizedString.status_ui_likes
    val statusUiBookmarks = localizedString.status_ui_bookmarks
    val statusUiEditProfile = localizedString.status_ui_edit_profile
    val statusUiLogout = localizedString.status_ui_logout
    val statusUiLogoutDialogContent = localizedString.status_ui_logout_dialog_content
    val statusUiSearchAccountStatusHint = localizedString.status_ui_search_account_status_hint

    val explorerSearchNoResults = localizedString.explorer_search_no_results
    val explorerSearchBarHint = localizedString.explorer_search_bar_hint
    val explorerSearchBarHintSpecializePlatform =
        localizedString.explorer_search_bar_hint_specialize_platform
    val explorerSearchTabTitleAuthor = localizedString.explorer_search_tab_title_author
    val explorerSearchTabTitleStatus = localizedString.explorer_search_tab_title_status
    val explorerSearchTabTitleLatest = localizedString.explorer_search_tab_title_latest
    val explorerSearchTabTitleTop = localizedString.explorer_search_tab_title_top
    val explorerSearchTabTitleHashtag = localizedString.explorer_search_tab_title_hashtag
    val explorerSearchTabTitleServer = localizedString.explorer_search_tab_title_server
    val explorerTabTitle = localizedString.explorer_tab_title
    val explorerTabStatusTitle = localizedString.explorer_tab_status_title
    val explorerTabUsersTitle = localizedString.explorer_tab_users_title
    val explorerTabHashtagTitle = localizedString.explorer_tab_hashtag_title

    val addProviderPageTitle = localizedString.add_provider_page_title
    val addProviderPageConfirmButton = localizedString.add_provider_page_confirm_button
    val searchPageTitle = localizedString.search_page_title
    val searchResultNotFound = localizedString.search_result_not_found
    val feedsImportPageTitle = localizedString.feeds_import_page_title
    val feedsImportPageHint = localizedString.feeds_import_page_hint
    val feedsImportButton = localizedString.feeds_import_button
    val addFeedsPageTitle = localizedString.add_feeds_page_title
    val addFeedsPageFeedsNameLabel = localizedString.add_feeds_page_feeds_name_label
    val addFeedsPageFeedsNameHint = localizedString.add_feeds_page_feeds_name_hint
    val addFeedsPageFeedsEmpty = localizedString.add_feeds_page_feeds_empty
    val preAddFeedsNoResult = localizedString.pre_add_feeds_no_result
    val preAddFeedsHint = localizedString.pre_add_feeds_hint
    val preAddFeedsInputLabel1 = localizedString.pre_add_feeds_input_label_1
    val preAddFeedsInputLabel2 = localizedString.pre_add_feeds_input_label_2
    val emptyContentHintTitle = localizedString.empty_content_hint_title
    val emptyContentHintDesc = localizedString.empty_content_hint_desc
    val feedsAddContent = localizedString.feeds_add_content
    val selectFeedsTypeScreenTitle = localizedString.select_feeds_type_screen_title
    val feedsPreAddLoginDialogContent = localizedString.feeds_pre_add_login_dialog_content
    val addFeedsPageEmptyNameTips = localizedString.add_feeds_page_empty_name_tips
    val addFeedsPageEmptySourceTips = localizedString.add_feeds_page_empty_source_tips
    val addFeedsChooseAuthDialogTitle = localizedString.add_feeds_choose_auth_dialog_title
    val searchFeedsTitle = localizedString.search_feeds_title
    val searchFeedsTitleHint = localizedString.search_feeds_title_hint
    val feedsSelectAccountForPostStatus = localizedString.feeds_select_account_for_post_status
    val feedsMixedConfigEditNewNameDialogTitle =
        localizedString.feeds_mixed_config_edit_new_name_dialog_title
    val feedsMixedConfigEditNewNameDialogLabel =
        localizedString.feeds_mixed_config_edit_new_name_dialog_label
    val feedsMixedConfigEditDeleteContentDialogMessage =
        localizedString.feeds_mixed_config_edit_delete_content_dialog_message
    val feedsMixedConfigNotFound = localizedString.feeds_mixed_config_not_found
    val feedsImportBackDialogMessage = localizedString.feeds_import_back_dialog_message
    val feedsDeleteConfirmContent = localizedString.feeds_delete_confirm_content
    val feedsSelectTypeScreenTitle = localizedString.feeds_select_type_screen_title
    val feedsSelectTypeScreenContent = localizedString.feeds_select_type_screen_content
    val notificationTabTitle = localizedString.notification_tab_title
    val notificationsAccountEmptyTip = localizedString.notifications_account_empty_tip
    val notificationsTabAll = localizedString.notifications_tab_all
    val notificationsTabMention = localizedString.notifications_tab_mention
    val profilePageTitle = localizedString.profile_page_title
    val profileSettingAboutTitle = localizedString.profile_setting_about_title
    val profileSettingDonateDesc = localizedString.profile_setting_donate_desc
    val profileSettingInlineVideoAutoPlay = localizedString.profile_setting_inline_video_auto_play
    val profileSettingInlineVideoAutoPlaySubtitle =
        localizedString.profile_setting_inline_video_auto_play_subtitle
    val profileSettingAlwaysShowSensitiveContent =
        localizedString.profile_setting_always_show_sensitive_content
    val profileSettingAlwaysShowSensitiveContentSubtitle =
        localizedString.profile_setting_always_show_sensitive_content_subtitle
    val profileSettingDarkModeTitle = localizedString.profile_setting_dark_mode_title
    val profileSettingDarkModeDark = localizedString.profile_setting_dark_mode_dark
    val profileSettingDarkModeLight = localizedString.profile_setting_dark_mode_light
    val profileSettingDarkModeFollowSystem = localizedString.profile_setting_dark_mode_follow_system
    val profileSettingOpenSourceTitle = localizedString.profile_setting_open_source_title
    val profileSettingOpenSourceDesc = localizedString.profile_setting_open_source_desc
    val profileSettingOpenSourceFeedback = localizedString.profile_setting_open_source_feedback
    val profileSettingOpenSourceFeedbackDesc =
        localizedString.profile_setting_open_source_feedback_desc
    val profileSettingOpenSourceFeedbackTelegram =
        localizedString.profile_setting_open_source_feedback_telegram
    val profileSettingOpenSourceFeedbackGithub =
        localizedString.profile_setting_open_source_feedback_github
    val profileSettingOpenSourceFeedbackEmail =
        localizedString.profile_setting_open_source_feedback_email
    val profileSettingLanguageTitle = localizedString.profile_setting_language_title
    val profileSettingLanguageZh = localizedString.profile_setting_language_zh
    val profileSettingLanguageEn = localizedString.profile_setting_language_en
    val profileSettingLanguageSystem = localizedString.profile_setting_language_system
    val profileSettingRatting = localizedString.profile_setting_ratting
    val profileSettingRattingDesc = localizedString.profile_setting_ratting_desc
    val profileSettingFontSize = localizedString.profile_setting_font_size
    val profileSettingFontSizeDesc = localizedString.profile_setting_font_size_desc
    val profileSettingFontSizeSmall = localizedString.profile_setting_font_size_small
    val profileSettingFontSizeMedium = localizedString.profile_setting_font_size_medium
    val profileSettingFontSizeLarge = localizedString.profile_setting_font_size_large
    val profileSettingImmersiveNavBar = localizedString.profile_setting_immersive_nav_bar
    val profileSettingImmersiveNavBarDesc = localizedString.profile_setting_immersive_nav_bar_desc
    val profileSettingTimelinePosition = localizedString.profile_setting_timeline_position
    val profileSettingTimelinePositionLastRead =
        localizedString.profile_setting_timeline_position_last_read
    val profileSettingTimelinePositionNewest =
        localizedString.profile_setting_timeline_position_newest
    val profileSettingThemeTitle = localizedString.profile_setting_theme_title
    val profileSettingThemeDefault = localizedString.profile_setting_theme_default
    val profileSettingThemeSystem = localizedString.profile_setting_theme_system
    val profileAboutVersion = localizedString.profile_about_version
    val profileAboutWebsite = localizedString.profile_about_website
    val profileAboutDeveloper = localizedString.profile_about_developer
    val profileAboutContractUs = localizedString.profile_about_contract_us
    val profileAboutTelegram = localizedString.profile_about_telegram
    val profileAboutPrivacyPolicy = localizedString.profile_about_privacy_policy
    val profileSettingCheckForUpdate = localizedString.profile_setting_check_for_update
    val profileSettingAlreadyLatestVersion = localizedString.profile_setting_already_latest_version
    val profileSettingHaveNewVersion = localizedString.profile_setting_have_new_version
    val profileDonatePageTitle = localizedString.profile_donate_page_title
    val profileAccountNotLogin = localizedString.profile_account_not_login

    val rss_source_detail_screen_title = localizedString.rss_source_detail_screen_title
    val rss_source_detail_screen_custom_title =
        localizedString.rss_source_detail_screen_custom_title
    val rss_source_detail_screen_url = localizedString.rss_source_detail_screen_url
    val rss_source_detail_screen_home_url = localizedString.rss_source_detail_screen_home_url
    val rss_source_detail_screen_add_date = localizedString.rss_source_detail_screen_add_date
    val rss_source_detail_screen_last_update_date =
        localizedString.rss_source_detail_screen_last_update_date

    val bluesky_protocol_name = localizedString.bluesky_protocol_name

    val bsky_add_content_title = localizedString.bsky_add_content_title
    val bsky_add_content_hosting_provider = localizedString.bsky_add_content_hosting_provider
    val bsky_add_content_user_name = localizedString.bsky_add_content_user_name
    val bsky_add_content_password = localizedString.bsky_add_content_password
    val bsky_add_content_factor_token = localizedString.bsky_add_content_factor_token

    val bsky_edit_content_title = localizedString.bsky_edit_content_title

    val bsky_feeds_explorer_more = localizedString.bsky_feeds_explorer_more
    val bsky_feeds_explorer_creator_label = localizedString.bsky_feeds_explorer_creator_label
    val bsky_feeds_explorer_liked_by = localizedString.bsky_feeds_explorer_liked_by
    val bsky_feeds_detail_creator_prefix = localizedString.bsky_feeds_detail_creator_prefix
    val bsky_feeds_item_subtitle = localizedString.bsky_feeds_item_subtitle

    val bsky_feeds_following_name = localizedString.bsky_feeds_following_name

    val bsky_feeds_user_posts = localizedString.bsky_feeds_user_posts
    val bsky_feeds_user_replies = localizedString.bsky_feeds_user_replies
    val bsky_feeds_user_medias = localizedString.bsky_feeds_user_medias
    val bsky_feeds_user_likes = localizedString.bsky_feeds_user_likes

    val bsky_user_detail_action_blocked_list = localizedString.bsky_user_detail_action_blocked_list
    val bsky_user_detail_action_muted_list = localizedString.bsky_user_detail_action_muted_list
    val bsky_user_detail_action_mute_user = localizedString.bsky_user_detail_action_mute_user
    val bsky_user_detail_action_unmute_user = localizedString.bsky_user_detail_action_unmute_user
    val bsky_user_detail_action_block_user = localizedString.bsky_user_detail_action_block_user
    val bsky_user_detail_action_unblock_user = localizedString.bsky_user_detail_action_unblock_user
    val bsky_user_detail_action_block_user_dialog_message =
        localizedString.bsky_user_detail_action_block_user_dialog_message
    val bsky_user_detail_action_mute_user_dialog_message =
        localizedString.bsky_user_detail_action_mute_user_dialog_message

    val bsky_edit_profile_title = localizedString.bsky_edit_profile_title

    val activity_pub_login_exception = localizedString.activity_pub_login_exception

    val activity_pub_home_timeline = localizedString.activity_pub_home_timeline
    val activity_pub_local_timeline = localizedString.activity_pub_local_timeline
    val activity_pub_public_timeline = localizedString.activity_pub_public_timeline

    val activity_pub_instance_detail_language_label =
        localizedString.activity_pub_instance_detail_language_label
    val activity_pub_instance_detail_active_month_label =
        localizedString.activity_pub_instance_detail_active_month_label

    val activity_pub_user_detail_join_date = localizedString.activity_pub_user_detail_join_date
    val activity_pub_user_detail_tab_post = localizedString.activity_pub_user_detail_tab_post
    val activity_pub_user_detail_tab_replies = localizedString.activity_pub_user_detail_tab_replies
    val activity_pub_user_detail_tab_media = localizedString.activity_pub_user_detail_tab_media
    val activity_pub_user_detail_tab_about = localizedString.activity_pub_user_detail_tab_about
    val activity_pub_user_detail_tab_about_joined =
        localizedString.activity_pub_user_detail_tab_about_joined
    val activity_pub_user_detail_menu_block = localizedString.activity_pub_user_detail_menu_block
    val activity_pub_user_detail_menu_block_domain =
        localizedString.activity_pub_user_detail_menu_block_domain
    val activity_pub_user_detail_menu_unblock_domain =
        localizedString.activity_pub_user_detail_menu_unblock_domain
    val activity_pub_user_detail_menu_edit_private_note =
        localizedString.activity_pub_user_detail_menu_edit_private_note
    val activity_pub_user_detail_menu_edit_private_note_dialog_hint =
        localizedString.activity_pub_user_detail_menu_edit_private_note_dialog_hint
    val activity_pub_user_detail_dialog_content_block =
        localizedString.activity_pub_user_detail_dialog_content_block
    val activity_pub_user_detail_dialog_content_block_domain =
        localizedString.activity_pub_user_detail_dialog_content_block_domain
    val activity_pub_user_menu_blocked_user_list =
        localizedString.activity_pub_user_menu_blocked_user_list
    val activity_pub_user_menu_muted_user_list =
        localizedString.activity_pub_user_menu_muted_user_list
    val activity_pub_user_detail_menu_mute_user =
        localizedString.activity_pub_user_detail_menu_mute_user
    val activity_pub_user_detail_menu_unmute_user =
        localizedString.activity_pub_user_detail_menu_unmute_user
    val activity_pub_mute_user_bottom_sheet_title =
        localizedString.activity_pub_mute_user_bottom_sheet_title
    val activity_pub_mute_user_bottom_sheet_role1 =
        localizedString.activity_pub_mute_user_bottom_sheet_role1
    val activity_pub_mute_user_bottom_sheet_role2 =
        localizedString.activity_pub_mute_user_bottom_sheet_role2
    val activity_pub_mute_user_bottom_sheet_role3 =
        localizedString.activity_pub_mute_user_bottom_sheet_role3
    val activity_pub_mute_user_bottom_sheet_role4 =
        localizedString.activity_pub_mute_user_bottom_sheet_role4
    val activity_pub_mute_user_bottom_sheet_btn_mute =
        localizedString.activity_pub_mute_user_bottom_sheet_btn_mute

    val activity_pub_about = localizedString.activity_pub_about
    val activity_pub_about_rule_title = localizedString.activity_pub_about_rule_title
    val activity_pub_trends_tag = localizedString.activity_pub_trends_tag
    val activity_pub_trends_tag_description = localizedString.activity_pub_trends_tag_description
    val activity_pub_trends_status = localizedString.activity_pub_trends_status

    val input_media_desc_page_title = localizedString.input_media_desc_page_title
    val input_media_desc_input_hint = localizedString.input_media_desc_input_hint

    val post_status_page_title = localizedString.post_status_page_title
    val post_screen_input_hint = localizedString.post_screen_input_hint
    val post_screen_media_descriptor_placeholder =
        localizedString.post_screen_media_descriptor_placeholder
    val post_status_poll_item_hint = localizedString.post_status_poll_item_hint
    val post_status_poll_duration = localizedString.post_status_poll_duration
    val post_status_poll_function_title = localizedString.post_status_poll_function_title
    val post_status_poll_single = localizedString.post_status_poll_single
    val post_status_poll_multiple = localizedString.post_status_poll_multiple
    val post_status_poll_style_select_dialog_title =
        localizedString.post_status_poll_style_select_dialog_title
    val post_status_poll_is_empty = localizedString.post_status_poll_is_empty
    val post_status_media_is_not_upload = localizedString.post_status_media_is_not_upload
    val error_video_too_large = localizedString.error_video_too_large
    val error_video_load_failed = localizedString.error_video_load_failed
    val error_video_upload_failed = localizedString.error_video_upload_failed
    val error_video_transcode_failed = localizedString.error_video_transcode_failed
    val error_video_transcode_timeout = localizedString.error_video_transcode_timeout

    val add_instance_screen_title = localizedString.add_instance_screen_title
    val add_instance_input_service_hint = localizedString.add_instance_input_service_hint
    val add_instance_input_service_error = localizedString.add_instance_input_service_error

    val activity_pub_content_tab_home = localizedString.activity_pub_content_tab_home
    val activity_pub_content_tab_local_timeline =
        localizedString.activity_pub_content_tab_local_timeline
    val activity_pub_content_tab_public_timeline =
        localizedString.activity_pub_content_tab_public_timeline
    val activity_pub_content_tab_trending = localizedString.activity_pub_content_tab_trending

    val activity_pub_hashtag_timeline_description =
        localizedString.activity_pub_hashtag_timeline_description
    val activity_pub_hashtag_unfollow_dialog_message =
        localizedString.activity_pub_hashtag_unfollow_dialog_message

    val activity_pub_edit_account_info_label_about =
        localizedString.activity_pub_edit_account_info_label_about

    val activity_pub_edit_content_screen_config_not_found =
        localizedString.activity_pub_edit_content_screen_config_not_found

    val activity_pub_user_list_empty = localizedString.activity_pub_user_list_empty

    val activity_pub_muted_user_list_empty = localizedString.activity_pub_muted_user_list_empty
    val activity_pub_muted_user_list_unmute = localizedString.activity_pub_muted_user_list_unmute

    val activity_pub_blocked_user_list_empty = localizedString.activity_pub_blocked_user_list_empty
    val activity_pub_blocked_user_list_unblock =
        localizedString.activity_pub_blocked_user_list_unblock

    val activity_pub_bookmarks_list_title = localizedString.activity_pub_bookmarks_list_title
    val activity_pub_favourites_list_title = localizedString.activity_pub_favourites_list_title

    val activity_pub_followed_tags_screen_title =
        localizedString.activity_pub_followed_tags_screen_title

    val activity_pub_filters_list_page_title = localizedString.activity_pub_filters_list_page_title
    val activity_pub_filters_active = localizedString.activity_pub_filters_active
    val activity_pub_filters_expired = localizedString.activity_pub_filters_expired

    val activity_pub_select_platform_title = localizedString.activity_pub_select_platform_title
    val activity_pub_select_platform_text_hint =
        localizedString.activity_pub_select_platform_text_hint

    val activity_pub_filter_edit_title = localizedString.activity_pub_filter_edit_title
    val activity_pub_filter_edit_input_title_label =
        localizedString.activity_pub_filter_edit_input_title_label
    val activity_pub_filter_edit_input_title_hint =
        localizedString.activity_pub_filter_edit_input_title_hint
    val activity_pub_filter_edit_duration = localizedString.activity_pub_filter_edit_duration
    val activity_pub_filter_edit_duration_permanent =
        localizedString.activity_pub_filter_edit_duration_permanent
    val activity_pub_filter_edit_duration_thirty_minutes =
        localizedString.activity_pub_filter_edit_duration_thirty_minutes
    val activity_pub_filter_edit_duration_one_hour =
        localizedString.activity_pub_filter_edit_duration_one_hour
    val activity_pub_filter_edit_duration_twelve_hours =
        localizedString.activity_pub_filter_edit_duration_twelve_hours
    val activity_pub_filter_edit_duration_one_day =
        localizedString.activity_pub_filter_edit_duration_one_day
    val activity_pub_filter_edit_duration_three_day =
        localizedString.activity_pub_filter_edit_duration_three_day
    val activity_pub_filter_edit_duration_one_week =
        localizedString.activity_pub_filter_edit_duration_one_week
    val activity_pub_filter_edit_duration_custom =
        localizedString.activity_pub_filter_edit_duration_custom
    val activity_pub_filter_edit_duration_finish_subtitle =
        localizedString.activity_pub_filter_edit_duration_finish_subtitle

    val activity_pub_filter_edit_keyword_title =
        localizedString.activity_pub_filter_edit_keyword_title
    val activity_pub_filter_edit_keyword_dialog_title =
        localizedString.activity_pub_filter_edit_keyword_dialog_title
    val activity_pub_filter_edit_keyword_dialog_hint =
        localizedString.activity_pub_filter_edit_keyword_dialog_hint
    val activity_pub_filter_edit_keyword_remove_keyword_dialog_content =
        localizedString.activity_pub_filter_edit_keyword_remove_keyword_dialog_content
    val activity_pub_filter_edit_keyword_list_title =
        localizedString.activity_pub_filter_edit_keyword_list_title
    val activity_pub_filter_edit_keyword_list_desc =
        localizedString.activity_pub_filter_edit_keyword_list_desc
    val activity_pub_filter_edit_context_title =
        localizedString.activity_pub_filter_edit_context_title
    val activity_pub_filter_edit_context_selector_title =
        localizedString.activity_pub_filter_edit_context_selector_title
    val activity_pub_filter_edit_context_home =
        localizedString.activity_pub_filter_edit_context_home
    val activity_pub_filter_edit_context_notification =
        localizedString.activity_pub_filter_edit_context_notification
    val activity_pub_filter_edit_context_timeline =
        localizedString.activity_pub_filter_edit_context_timeline
    val activity_pub_filter_edit_context_thread =
        localizedString.activity_pub_filter_edit_context_thread
    val activity_pub_filter_edit_context_account =
        localizedString.activity_pub_filter_edit_context_account
    val activity_pub_filter_edit_empty_context =
        localizedString.activity_pub_filter_edit_empty_context
    val activity_pub_filter_edit_warning_title =
        localizedString.activity_pub_filter_edit_warning_title
    val activity_pub_filter_edit_warning_desc =
        localizedString.activity_pub_filter_edit_warning_desc
    val activity_pub_filter_edit_delete_content =
        localizedString.activity_pub_filter_edit_delete_content
    val activity_pub_filter_edit_back_dialog = localizedString.activity_pub_filter_edit_back_dialog
    val activity_pub_filter_edit_whole_word = localizedString.activity_pub_filter_edit_whole_word

    val activity_pub_explorer_tab_status_title =
        localizedString.activity_pub_explorer_tab_status_title
    val activity_pub_explorer_tab_users_title =
        localizedString.activity_pub_explorer_tab_users_title
    val activity_pub_explorer_tab_hashtag_title =
        localizedString.activity_pub_explorer_tab_hashtag_title

    val activity_pub_created_list_title = localizedString.activity_pub_created_list_title
    val activity_pub_add_list_title = localizedString.activity_pub_add_list_title
    val activity_pub_add_list_name = localizedString.activity_pub_add_list_name
    val activity_pub_add_list_replies = localizedString.activity_pub_add_list_replies
    val activity_pub_add_list_replies_non = localizedString.activity_pub_add_list_replies_non
    val activity_pub_add_list_replies_list = localizedString.activity_pub_add_list_replies_list
    val activity_pub_add_list_replies_followers =
        localizedString.activity_pub_add_list_replies_followers
    val activity_pub_add_list_accounts = localizedString.activity_pub_add_list_accounts
    val activity_pub_add_list_hide_in_timeline =
        localizedString.activity_pub_add_list_hide_in_timeline
    val activity_pub_add_list_hide_in_timeline_desc =
        localizedString.activity_pub_add_list_hide_in_timeline_desc
    val activity_pub_add_list_remove_user_message =
        localizedString.activity_pub_add_list_remove_user_message
    val activity_pub_add_list_name_is_empty = localizedString.activity_pub_add_list_name_is_empty
    val activity_pub_add_list_back_reminder = localizedString.activity_pub_add_list_back_reminder
    val activity_pub_search_user_placeholder = localizedString.activity_pub_search_user_placeholder
    val activity_pub_list_delete_confirm = localizedString.activity_pub_list_delete_confirm

    val mixed_content_subtitle_1 = localizedString.mixed_content_subtitle_1
    val mixed_content_subtitle_2 = localizedString.mixed_content_subtitle_2
    val date_time_ago = localizedString.date_time_ago
    val date_time_ago_prefix = localizedString.date_time_ago_prefix
    val date_time_ago_suffix = localizedString.date_time_ago_suffix
    val date_time_day = localizedString.date_time_day
    val date_time_hour = localizedString.date_time_hour
    val date_time_minute = localizedString.date_time_minute
    val date_time_second = localizedString.date_time_second

    val authentication_page_normal_title = localizedString.authentication_page_normal_title
    val authentication_page_failed_title = localizedString.authentication_page_failed_title
    val main_drawer_title = localizedString.main_drawer_title
    val main_drawer_mixed_item_subtitle_1 = localizedString.main_drawer_mixed_item_subtitle_1
    val main_drawer_mixed_item_subtitle_2 = localizedString.main_drawer_mixed_item_subtitle_2
    val main_drawer_settings = localizedString.main_drawer_settings
    val main_drawer_donate = localizedString.main_drawer_donate
    val main_request_notification_dialog_title =
        localizedString.main_request_notification_dialog_title
    val main_request_notification_dialog_reject_button =
        localizedString.main_request_notification_dialog_reject_button
    val main_request_notification_dialog_allow_button =
        localizedString.main_request_notification_dialog_allow_button
    val main_request_notification_dialog_content =
        localizedString.main_request_notification_dialog_content
    val status_ui_embed_quote_unavailable = localizedString.status_ui_embed_quote_unavailable
    val status_ui_action_unforward = localizedString.status_ui_action_unforward
    val status_ui_quote_approval_public = localizedString.status_ui_quote_approval_public
    val status_ui_quote_approval_follower = localizedString.status_ui_quote_approval_follower
    val status_ui_quote_approval_nobody = localizedString.status_ui_quote_approval_nobody
    val status_ui_visibility = localizedString.status_ui_visibility
    val setting_item_amoled_mode = localizedString.setting_item_amoled_mode
    val setting_item_amoled_mode_description = localizedString.setting_item_amoled_mode_description
    val setting_group_appearance = localizedString.setting_group_appearance
    val setting_group_appearance_subtitle = localizedString.setting_group_appearance_subtitle
    val setting_group_behavior = localizedString.setting_group_behavior
    val setting_group_behavior_subtitle = localizedString.setting_group_behavior_subtitle
    val setting_item_home_tab_next_title = localizedString.setting_item_home_tab_next_title
    val setting_item_home_tab_next_subtitle = localizedString.setting_item_home_tab_next_subtitle
    val setting_item_home_tab_refresh_title = localizedString.setting_item_home_tab_refresh_title
    val setting_item_home_tab_refresh_subtitle =
        localizedString.setting_item_home_tab_refresh_subtitle
    val setting_item_open_url_by_system_title =
        localizedString.setting_item_open_url_by_system_title
    val setting_item_open_url_by_system_subtitle =
        localizedString.setting_item_open_url_by_system_subtitle
    val setting_item_solid_bar_background_title =
        localizedString.setting_item_solid_bar_background_title
    val setting_item_solid_bar_background_subtitle =
        localizedString.setting_item_solid_bar_background_subtitle
    val setting_item_jump_to_profile_title =
        localizedString.setting_item_jump_to_profile_title
    val setting_item_jump_to_profile_subtitle =
        localizedString.setting_item_jump_to_profile_subtitle
    val bluesky_user_list_tab_boosts = localizedString.bluesky_user_list_tab_boosts
    val bluesky_user_list_tab_quotes = localizedString.bluesky_user_list_tab_quotes
    val setting_group_following_feed_title =
        localizedString.setting_group_following_feed_title
    val setting_group_following_feed_subtitle =
        localizedString.setting_group_following_feed_subtitle
    val setting_item_hide_replies_title =
        localizedString.setting_item_hide_replies_title
    val setting_item_hide_replies_subtitle =
        localizedString.setting_item_hide_replies_subtitle
    val setting_item_hide_replies_by_unfollowed_title =
        localizedString.setting_item_hide_replies_by_unfollowed_title
    val setting_item_hide_replies_by_unfollowed_subtitle =
        localizedString.setting_item_hide_replies_by_unfollowed_subtitle
    val setting_item_hide_reposts_title =
        localizedString.setting_item_hide_reposts_title
    val setting_item_hide_reposts_subtitle =
        localizedString.setting_item_hide_reposts_subtitle
    val setting_item_hide_quote_posts_title =
        localizedString.setting_item_hide_quote_posts_title
    val setting_item_hide_quote_posts_subtitle =
        localizedString.setting_item_hide_quote_posts_subtitle
    val alt_text_settings_title = localizedString.alt_text_settings_title
    val alt_text_settings_subtitle_configured =
        localizedString.alt_text_settings_subtitle_configured
    val alt_text_settings_subtitle_not_configured =
        localizedString.alt_text_settings_subtitle_not_configured
    val alt_text_settings_api_key_label = localizedString.alt_text_settings_api_key_label
    val alt_text_settings_base_url_label = localizedString.alt_text_settings_base_url_label
    val alt_text_settings_model_label = localizedString.alt_text_settings_model_label
    val alt_text_settings_prompt_label = localizedString.alt_text_settings_prompt_label
    val alt_text_settings_max_tokens_label = localizedString.alt_text_settings_max_tokens_label
    val alt_text_settings_save = localizedString.alt_text_settings_save
    val alt_text_generate_button = localizedString.alt_text_generate_button
    val alt_text_cancel_button = localizedString.alt_text_cancel_button
    val alt_text_provider_format = localizedString.alt_text_provider_format
    val alt_text_cost_format = localizedString.alt_text_cost_format
    val error_alt_text_not_configured = localizedString.error_alt_text_not_configured
    val error_alt_text_load_image = localizedString.error_alt_text_load_image
    val error_alt_text_server = localizedString.error_alt_text_server
    val error_alt_text_network = localizedString.error_alt_text_network
    val error_alt_text_no_text = localizedString.error_alt_text_no_text
    val threaded_view_menu_open = localizedString.threaded_view_menu_open
    val threaded_view_screen_title = localizedString.threaded_view_screen_title
    val threaded_view_assembling = localizedString.threaded_view_assembling
    val threaded_view_empty = localizedString.threaded_view_empty
    val threaded_view_back = localizedString.threaded_view_back
}
